libddwaf.gemspec

Since <https://github.com/DataDog/libddwaf-rb> is where the Ruby code is, I think it makes sense to have it as the `homepage` in the gemspec.
Interested customers can always follow the link to the upstream libddwaf in the README.md.

Set homepage in gemspec to libddwaf-rb repository

---

lib/datadog/appsec/waf.rb

When parsing the input we were not using the right constant when calling `ruby_to_object`. The constant previously used was `DDWAF_MAX_CONTAINER_SIZE` which is 256. That value was use as the max length a string could be. 
That was causing issues with long input types.
Fix: Use the right constant `DDWAF_MAX_STRING_LENGTH` with a value of 4096

set correct max string length when running

---

lib/datadog/appsec/waf.rb

Steep tries to understand this comment as a typing directive. Padding with more text to cue it into not doing that.

Work around Steep parsing

---

lib/datadog/appsec/waf.rb

These two methods were not releasing the ddwaf objects that were created from their arguments, thus each call leaked memory.

Free transient objects for update methods

---

.rubocop.yml
CHANGELOG.md
Rakefile
lib/datadog/appsec/waf.rb
lib/datadog/appsec/waf/version.rb
sig/datadog/appsec/waf.rbs
spec/datadog/appsec/waf_spec.rb

Base on the latest release from libddwaf 1.6.2 . Only one new function has been added to the library `ddwaf_object_get_bool`
Compare between previous version [1.5.1 and 1.6.2](https://github.com/DataDog/libddwaf/compare/1.5.1...1.6.2#diff-b237790755a7680c602d8e294ac9fa8efd9d94f834e52db8be31410d727f1dd0R634)
libddwaf updated the logic when filtering input https://github.com/DataDog/libddwaf/pull/117. Because of that I had to modify a test in the codebase.

[APPSEC-7802] Release v1.6.2.0.0

---

CHANGELOG.md
Gemfile
Rakefile
lib/datadog/appsec/waf/version.rb

Update to use libddwaf 1.7.0
There are no API changes with the [1.7.0 release](https://github.com/DataDog/libddwaf/blob/master/UPGRADING.md#upgrading-from-16x-to-170). 
The most significant change has been done internally with the lifecycle of [handle and context](https://github.com/DataDog/libddwaf/pull/135) 
I had to update the `rbs`, and `steep` dependencies because the [CI was failing ](https://github.com/DataDog/libddwaf-rb/actions/runs/4304556257/jobs/7507360038)

[APPSEC-8457] Update libddwaf to 1.7.0

---

Gemfile
Rakefile
lib/datadog/appsec/waf/version.rb
spec/datadog/appsec/waf_spec.rb

Upgrade libddwaf to 1.9.0
Here is the diff between [1.82 and 1.9.0](https://github.com/DataDog/libddwaf/compare/1.8.2...1.9.0)
The biggest change for us, is that we can now pass `custom_rules` to WAF init and merege

Upgrade libddwaf to 1.9.0. Add support for `custom_rules`

---

Rakefile
lib/datadog/appsec/waf/version.rb

Bump version to `1.10.0`
The libddwaf [1.10.0 has no breaking changes](https://github.com/DataDog/libddwaf/releases/tag/1.10.0) so no need to worry about changing the internals of libddwaf-rb
**Motivation**

Bump version to 1.10.0

---

.rubocop.yml
CHANGELOG.md
Rakefile
lib/datadog/appsec/waf.rb
lib/datadog/appsec/waf/version.rb
sig/datadog/appsec/waf.rbs
spec/datadog/appsec/waf_spec.rb

Bump version to 1.11.0
Breaking changes 
- RulesetInfo has been replace with a LibDDWAF::Object
- Result#data has been replaced with a LibDDWAF::Object and renamed to events
- Result#action has been replaced with a LibDDWAF::Object
More information on https://github.com/DataDog/libddwaf/blob/master/UPGRADING.md#upgrading-from-1100-to-1110

[APPSEC-9341] Release 1.11.0

---

.github/workflows/lint.yml
CHANGELOG.md
Rakefile
Steepfile
lib/datadog/appsec/waf.rb
lib/datadog/appsec/waf/version.rb
sig/datadog/appsec/waf.rbs
spec/datadog/appsec/waf_spec.rb

Update libddwaf to latest version `1.14.0` https://github.com/DataDog/libddwaf/releases/tag/1.14.0
**Motivation**
For the API secuirty work we are currently doing, we need the latest change from `1.14.0` version. The latest version allows us to extract the schema information from the waf addresses when provided with the correct configuration. 

[APPSEC-10967] Release 1.14.0

---

lib/datadog/appsec/waf.rb
lib/datadog/appsec/waf/version.rb
sig/datadog/appsec/waf.rbs
spec/datadog/appsec/waf_spec.rb

It renames function `ddwaf_required_addresses` to `ddwaf_known_addresses`.
**Motivation**
This function name was changed in `libddwaf` version `1.15.0`, according to the changelog:
https://github.com/DataDog/libddwaf/blob/master/UPGRADING.md#interface-changes

Rename `ddwaf_required_addresses` to `ddwaf_known_addresses`

---

.github/actions/docker-build-ruby/action.yml
.github/workflows/package.yml
.github/workflows/test.yml
Rakefile

We changing back to generic release page url for `fetch` rake task. This PR slightly improves readability

Refactor rake fetch task with release download

---

Rakefile

It makes sense to remove this task since we are not using it in out CI.
**Motivation**
This rake task is not used.
Nope
```
bundle exec rake --tasks
```
It seems they are not needed anymore, and .docker folder with
Dockerfiles does not exist.

Remove rake ci task

---

Rakefile

This PR removes `docker` rake tasks, since they are obsolete.
**Motivation**
It seems that `.docker` folder that contained dockerfiles was deleted some time ago, and these tasks are broken.
Nope
```
bundle exec rake --tasks
```

Remove obsolete docker rake tasks

---

Rakefile
lib/datadog/appsec/waf/version.rb

Unfortunately, the archive filename has changed for `libddwaf` releases from version `1.16.0`.
Now the release file name consists of CPU architecture, OS and `-musl` prefix. Again unfortunately, this change is only for linux releases.
Another catch is that the extracted folder name is still in the old format.
This PR changes the expected archive filename for versions of `libddwaf` newer than `1.16.0`.
**Motivation**
None
None
```bash
bundle exec rake libddwaf:fetch
```

Update libddwaf to 1.16.1, fix `libddwaf:fetch` task

---

lib/datadog/appsec/waf/version.rb
spec/datadog/appsec/waf/lib_ddwaf_spec.rb
spec/datadog/appsec/waf_spec.rb

Upgrading `libddwaf` to 1.18.0
**Motivation**
In 1.18.0 SQLi detector was introduced
There is a change in interface of actions, but it didn't break libddwaf-rb itself
```
appsec-app-generator $ bin/run -b raw-sqli
```

[APPSEC-55683] Upgrade libddwaf to 1.18

---

Rakefile
lib/datadog/appsec/waf/lib_ddwaf.rb

This PR fixes installation and execution of libddwaf-rb on JRuby on MacOS
**Motivation**
I wanted to test our RSpec testsuite using JRuby on MacOS but could not download nor use libddwaf library
**Additional notes**
I did not added a Github Action task for this, as the only use case for this is dockerless dev env
Install JRuby with rbenv, and run `bundle install`, `bundle exec rake extract` and `bundle exec rake spec`

Add support for JRuby on macOS

---

lib/datadog/appsec/waf/context.rb

Fix memory leaks
**Motivation**
It was impacting calls with ephemeral data
In addition we empty the list of retained objects on context finalization
CI

Release memory allocated for ephemeral data

---

lib/datadog/appsec/waf/version.rb
spec/datadog/appsec/waf/handle_spec.rb

This PR updates libddwaf to 1.19.1
**Motivation**
We need to update `libddwaf` to a more recent version.
WAF Handle cannot be created without rules after [PR#314](https://github.com/DataDog/libddwaf/pull/314/files#diff-d067197e9befed2abc2cac3d47e95a647139db7939bd1a1334a1b51a4c257864R198-R201), this is why we are changing tests.
CI

Update libddwaf to 1.19.1

---

Rakefile

It fixes the `binary` rake task when building a JRuby gem version on MacOS.
**Motivation**
The rake task is broken.
None.
CI and manual testing.

Fix parsing of the platform in Rakefile

---

lib/datadog/appsec/waf/version.rb

It updates `libddwaf` to 1.24.1
**Motivation**
This should be a quick update without any breaking changes.
None.
CI and manual testing.

Update libddwaf to 1.24.1

---

lib/datadog/appsec/waf/handle.rb

It removes one unnecessary comment - we have a memory leak test to ensure that this method is not leaking memory.
**Motivation**
I have found this comment in the code.
None.
-

Remove obsolete TODO comment

---

CHANGELOG.md
lib/datadog/appsec/waf/version.rb

It bumps the version of the gem to 1.24.1.1.0.
**Motivation**
We want to release a new version with caching in `Handle#known_addresses` and `LibDDWAF::Object.input_truncated?`.
This is kinda like a minor bump, but we are not changing `libddwaf` version, that's why 1.24.1.1.0.
CI.

Bump version to 1.24.1.1.0

---

lib/datadog/appsec/waf/converter.rb
libddwaf.gemspec
spec/datadog/appsec/waf/converter_spec.rb

Fixes #94
It fixes conversion for a Hash that has a `nil` key.
**Motivation**
https://github.com/DataDog/libddwaf-rb/issues/94
https://github.com/DataDog/dd-trace-rb/issues/4885
None.
CI should be enough.

Fix conversion for a Hash with nil key

---

.standard_todo.yml
CHANGELOG.md
Gemfile
lib/datadog/appsec/waf/context.rb
lib/datadog/appsec/waf/converter.rb
lib/datadog/appsec/waf/lib_ddwaf.rb
lib/datadog/appsec/waf/result.rb
lib/datadog/appsec/waf/version.rb
sig/datadog/appsec/waf.rbs
sig/datadog/appsec/waf/converter.rbs
sig/datadog/appsec/waf/lib_ddwaf.rbs
sig/datadog/appsec/waf/result.rbs
spec/datadog/appsec/waf/context_spec.rb
spec/datadog/appsec/waf/context_stress_test_spec.rb
spec/datadog/appsec/waf/lib_ddwaf_spec.rb
spec/datadog/appsec/waf/result_spec.rb

An upgrade to [libddwaf 1.25.1](https://github.com/DataDog/libddwaf/blob/master/UPGRADING.md#upgrading-from-124x-to-1250) and general overhaul of broken type specs, naming and outdated development gems.
**Motivation**
The overhaul during a breaking change is easier to incorporate into the PR, so I did it.
None.
CI should cover most of the cases.

Upgrade to 1.25.1

---

CHANGELOG.md
lib/datadog/appsec/waf/handle_builder.rb
lib/datadog/appsec/waf/version.rb
spec/datadog/appsec/waf/context_spec.rb
spec/datadog/appsec/waf/handle_builder_spec.rb
spec/datadog/appsec/waf/handle_spec.rb
spec/fixtures/valid_config.json

Disable coercion of some primitives into strings for rulesets
**Motivation**
New rulesets require now values like numbers to be distinguished from strings.
I would like to release it as minor patch instead of fix patch to reduce possible blast radius.
CI

[APPSEC-59241] Fix ruleset primitives coercion
